SELECT COMPANY
FROM CUSTOMERS
WHERE CUST_REP =	(	SELECT EMPL_NUM
						FROM SALESREPS
						WHERE NAME = 'Sue Smith')
AND NOT EXISTS		(	SELECT *
						FROM ORDERS
						WHERE CUST = CUST_NUM
						AND AMOUNT > 3000);