select COMPANY
FROM CUSTOMERS
WHERE CUST_NUM IN	(
						SELECT DISTINCT CUST
						FROM ORDERS
						WHERE MFR = 'ACI'
						AND PRODUCT LIKE '4100%'
						AND ORDER_DATE BETWEEN '2008-01-01'
										AND '2008-06-30'
					)